import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <h1>Shop</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
